### ISSUE TITLE
Always require optional field in python target

### ISSUE THREAD

**Issue by admire93** [spoqa/nirum#70]
```
record foo (
  text? optional-data
);
```

Above `foo` record compiled to

```
class Foo:
    ...

    def __init__(self, optional_data: typing.Optional[str]) -> None:
        ...
```

It requires `optional_data` as a argument to initiate class `Foo`, although `optional_data` is optional.

**Comment by dahlia** [comment]
Should we treat it as a bug?  I'm not sure.  Think of the following example:

```nirum
record bar (
    text a,
    text? b,
    text c,
    text? d,
);
```

It consists of two required fields and two optional fields, and they appear by turns.  So should it be compiled to `__init__(self, a: str, b: Optional[str]=None, c: str, d: Optional[str]=None)`?  As you probably are aware of, it is not a valid Python syntax since Python doesn't allow optional argument followed by required argument.

**Comment by dahlia** [comment]
There could be some ways.  One way is making `__init__()` method to take *only* keyword arguments (e.g. `__init__(self, *, a: str, b: Optional[str]=None, c: str, d: Optional[str]=None)`).

**Comment by dahlia** [comment]
Now it becomes harder to be keyword-only than before, since now Python target has Python 2 generator as well.  Whereas Python 3 has a operator for keyword-only parameters ([PEP 3102][1]), Python 2 does not.  In order to implement keyword-only parameters in Python 2, we need some tricks:

```python
def __init__(self, **kwargs):
    invalid_params = frozenset(kwargs) - {'a', 'b', 'c', 'd'}
    if invalid_params:
        raise TypeError('unexpected keywords: ' + ', '.join(invalid_params))
    ...
```

[1]: https://www.python.org/dev/peps/pep-3102/

**Comment by earlbread** [comment]
👀
